### ISSUE TITLE
'description' field not updating and submitting with commits

### ISSUE THREAD

**Issue by varora1406** [streamich/git-cz#188]
I have tried description field many times, and it's broken for quite a few time.
Below is the image where I entered description
![image](https://user-images.githubusercontent.com/24986539/86539576-4623e080-bf1b-11ea-84ad-d581166b8626.png)

And now, below image on github, where no description is sent with commit
![image](https://user-images.githubusercontent.com/24986539/86539586-5c31a100-bf1b-11ea-9a94-2ee946d25249.png)

Current version at my end of `git cz` - 4.5.0

**Comment by ArrayKnight** [comment]
I'm also running into the issue that the "BREAKING CHANGE" message doesn't show up in the commit message/body either

**Comment by ArrayKnight** [comment]
@StanLindsey @streamich This is a major issue with a breaking change that doesn't allow for a major version to be created. Can you please look at this soon?

**Comment by ArrayKnight** [comment]
Starting to track this down:

- To get started, I forked the repo and figured out that you can run `node lib/cli` to run a local version of the cli
- I added a `console.log({ state, message })` on https://github.com/streamich/git-cz/blob/master/lib/cli.js#L65 to verify that the interactive prompt responses were being correctly gathered and formatted into a message
- I verified that it was working as expected by running the cli with the `--dry-run` option
- Everything appeared corrected and the output command that would be run appeared correct
- I copied and ran the git commit command manually and got the full commit message in my repo
- I then made a minor edit and reran the cli without the `--dry-run` option, passing all of the same prompt responses
- I then verified that the second commit message was missing all details after the first line
- Bug has been reproduced

Next I'll be looking into the `executeCommand` method: https://github.com/streamich/git-cz/blob/master/lib/cli.js#L14

**Comment by ArrayKnight** [comment]
https://github.com/streamich/git-cz/blob/master/lib/cli.js#L16

Things I've tried and not found any success with:

- Passing commands and args directly in, without formatting
- Split up `formattedMessage` so that the command `git commit` was first parameter to `spawn`, and `--message "..."` was the string value in the array as the second paramter
- Tried different options for `shell` and `stdio` and `windowsVerbatimArguments` in `spawn`
- Used different versions of node (12.18.2, 13.11.0, 14.8.0)

Things that could be tried next (but I don't have time right now):

- Use a different command line / terminal
- Use a different version of Git Bash (I'm currently using v2.28.0)
- ???

It would also be good to know if this is a cross platform issue or not.

@xxholly32 @varora1406 

- What OS are you using? Which version?
- Which command line / terminal? Which version?
- What version of Node are you using?
- Are you using NPM or Yarn? Which version?

**Comment by ArrayKnight** [comment]
Also, just for clarity, the long description, BREAKING CHANGE, and linked issues are all missing from the commit message as mentioned in https://github.com/streamich/git-cz/issues/197
