### ISSUE TITLE
git cz -a not working?

### ISSUE THREAD

**Issue by abcfy2** [streamich/git-cz#189]
In the past version, I can pass some `git commit` args to `git cz`, E.g: `git cz -a`.

But I found it's not working since the latest version. Did you remove this feature?

**Comment by jimmy-guzman** [comment]
I think it's only broken in the scenario when running `git cz -a` when there's no stage files which is because of this change [https://github.com/streamich/git-cz/commit/c283ad3fac13eaf00a899b49da474c7608a61708]. 

One potential fix is to just not to check fo staged files if `-a` or `--amend` is passed.

**Comment by rodrigograca31** [comment]
@jimmy-guzman only saw you had a PR for this after I made mine..... :cry: 
sorry, but I will go with my version just because it avoids using an extra variable...

**Comment by jimmy-guzman** [comment]
@jimmy-guzman sounds good 👍
