### ISSUE TITLE
Emoji's not working in commit messages

### ISSUE THREAD

**Issue by victorjpe** [streamich/git-cz#285]
Hi, I have used `git-cz` in my project and hasn't disabled emoji's, however emoji's are not displayed in commit message.

I have have created a sample project where the issue can be observed: https://github.com/victorjpe/misty-forest. 
I would really like to use emoji's with commit. Please let me know what went wrong with my config ?

**Comment by victorjpe** [comment]
I am haven't used any config, I am beginning to doubt if is it caused by using commitizen

**Comment by victorjpe** [comment]
Will you able to share your Sample project here ? So I can compare with your dependencies ?

**Comment by DataHearth** [comment]
I've used your project as it is.

**Comment by DataHearth** [comment]
@victorjpe I've found your problem. It's due to the configuration inside the `package.json` file.
You should run this command in your repo:
```bash
npm install -g commitizen git-cz
commitizen init git-cz --save-dev --save-exact
```
Your actual configuration looks like this:
```json
"config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog-emoji"
    }
  }
```

But it should look more something like this:
```json
"config": {
    "commitizen": {
      "path": "./node_modules/git-cz"
    }
  }
```

You're using a different adapter than `git-cz`. That's why you're not getting emoji's from the default shipped configuration.

**Comment by victorjpe** [comment]
Thanks @DataHearth, it's working for me now. Thanks for the solution
